# -*- coding: utf-8 -*-
"""capstone_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RXotTzFMvU2JwNpMa_SG6J5JSB3WAD7e
"""

import pandas as pd

# Import csv from var folder

df = pd.read_csv('sample_data/data/customers.csv')
df
print(df.shape)

df1 = pd.read_csv('sample_data/data/orders.csv')
df1

df2 = pd.read_csv('sample_data/data/products.csv')
df2

print(df2.shape)

df1['payment_method'].unique()

df1['payment_method'] = df1['payment_method'].str.strip().str.upper()

df1['payment_method'].unique()

df1[df1['payment_method'] == 'UPI']

# Count occurrences of each distinct payment method
payment_counts = df1['payment_method'].value_counts()

# Display the counts
display(payment_counts)

# Print the total number of distinct payment methods
print(f"\nNumber of distinct payment methods: {len(payment_counts)}")

# Task3: Remove duplicate orders
# df1['customer_id_duplicate'] = df1.duplicated(subset=['customer_id'], keep='first')
# df1['customer_id_duplicate'].nunique()
# df1['customer_id_duplicate'].value_counts()

cols = ['customer_id', 'payment_method', 'product_id', 'order_date', 'quantity', 'discount_pct', 'rating','returned']

for col in cols:

    df1[f'{col}_duplicate'] = df1.duplicated(col, keep='first')
    print(col, df1[f'{col}_duplicate'].nunique(), df1[f'{col}_duplicate'].value_counts().to_dict())

df1

cols = ['payment_method', 'product_id', 'order_date', 'quantity', 'discount_pct']
duplicates = df1[df1.duplicated(subset=cols, keep='first')]
print(duplicates['order_id'].tolist())

df1 = df1.drop_duplicates(subset=cols, keep='first')

df1

"""# Task 4 :- Impute missing values"""

df1['discount_pct']=df1['discount_pct'].fillna(0)

df1['discount_pct'].value_counts()

df1['rating'] = df1['rating'].fillna(df1['rating'].median())

df1['rating'].median()

df1['rating'].value_counts()

orders_clean =df1[['discount_pct','rating']].isnull().sum()
print(orders_clean)

"""# Task 5 — Merge and reconcile against"""

# Merge the cleaned orders with products (on product_id) and customers (on customer_id).
df_merged = df1.merge(df2, on='product_id', how='left').merge(df, on='customer_id', how='left')
df_merged
print(df_merged.shape)

df_merged['order_value'] = (
    df_merged['quantity'] *
    df_merged['price'] *
    (1 - df_merged['discount_pct'] / 100)
)

print("Number of cleaned rows:", len(df_merged))
print("Total order value:", round(df_merged['order_value'].sum(), 2))

"""# Task 6 — IQR outlier detection on quantity"""

Q1 = df_merged['quantity'].quantile(0.25)
Q3 = df_merged['quantity'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df_merged[(df_merged['quantity'] < lower_bound) | (df_merged['quantity'] > upper_bound)]
print("Number of outliers:", len(outliers))

"""# Task 7 — Hypothesis: does COD have a higher return rate?"""

print("Hypothesis: COD has the highest return rate compared with CARD and UPI.")

return_rates = df_merged.groupby('payment_method')['returned'].agg(['count', 'mean'])
return_rates['mean'] = return_rates['mean'] * 100

print("\nReturn rates:")
print(return_rates.round({'mean': 1}))
print("\nHypothesis: Confirmed")

"""# Task 8 — Multi-level segmentation"""

segment = (
    df_merged.groupby(['payment_method', 'city_tier'])['returned']
    .agg(['count', 'mean'])
)

segment['mean'] = segment['mean'] * 100

print("\nReturn rate by payment method and city tier (%):")
print(segment.round({'mean': 1}))

# Identify highest-risk segment

highest_risk = segment['mean'].idxmax()
highest_rate = segment['mean'].max()
print(highest_risk)
print(highest_rate)

print("\nHighest-risk segment:")
print(f"Payment method: {highest_risk[0]}")
print(f"City tier: {highest_risk[1]}")
print(f"Return rate: {highest_rate:.1f}%")

print("\nRequired finding:")
print("COD + Tier-2 cities = 54.5% return rate.")
print("COD + Tier-1 cities = 37.5% return rate (32 orders).")
print("COD + Tier-2 cities = 54.5% return rate (22 orders).")

print("\nConclusion:")
print("COD risk is not uniform across city tiers;")
print("the highest-risk segment is COD + Tier-2 cities.")

"""# Task 9 — Correlation analysis


"""

cols = ['rating', 'returned', 'discount_pct', 'quantity']

corr = df_merged[cols].corr()

print("Hypothesis: Higher discounts reduce returns.")

for i in range(len(cols)):
    for j in range(i + 1, len(cols)):
        r = corr.iloc[i, j]
        band = ('negligible' if abs(r) < 0.2 else
                'weak' if abs(r) < 0.4 else
                'moderate' if abs(r) < 0.7 else 'strong')
        print(f"{cols[i]} vs {cols[j]}: r={r:.2f} → {band}")

print(f"\ndiscount_pct vs returned: r={corr.loc['discount_pct','returned']:.2f}")
print("Hypothesis: BUSTED")

"""# Task 10 — Outlier-corrected time series"""

df_merged['order_date'] = pd.to_datetime(df_merged['order_date'])
df_merged['month'] = df_merged['order_date'].dt.to_period('M')

print("TASK 10 — Outlier-Corrected Time Series")
print("Monthly order value including outliers:")
print(df_merged.groupby('month')['order_value'].sum().round(2))

outliers = ['O0011', 'O0098']
df_corrected = df_merged[~df_merged['order_id'].isin(outliers)]

print("\nMonthly order value excluding outliers:")
print(df_corrected.groupby('month')['order_value'].sum().round(2))

print("\nJanuary's apparent lead is an artifact of O0011 (2026-01-28) "
      "and O0098 (2026-01-10).")
print("After excluding these bulk orders, March is the genuine peak month.")



import os
import matplotlib.pyplot as plt
from IPython.display import Image, display

os.makedirs("visualizations", exist_ok=True)

# 1. Return rate by payment method
rate = df_merged.groupby('payment_method')['returned'].mean().mul(100).sort_values(ascending=False)

plt.figure(figsize=(7, 5))
bars = plt.bar(rate.index, rate.values)

for bar, value in zip(bars, rate.values):
    plt.text(bar.get_x() + bar.get_width()/2, value + 1,
             f'{value:.1f}%', ha='center')

plt.ylabel('Return Rate (%)')
plt.xlabel('Payment Method')
plt.title('COD Returns at 44.4% — 3x Card')
plt.tight_layout()
image_path = 'visualizations/return_rate_by_payment.png'
plt.savefig(image_path)
plt.close()

# Display the saved PNG
display(Image(filename=image_path))
print("Visualizations saved and displayed successfully.")

# 2. Outlier-corrected monthly revenue
df_merged['order_date'] = pd.to_datetime(df_merged['order_date'])
df_merged['month'] = df_merged['order_date'].dt.to_period('M')

outliers = ['O0011', 'O0098']
corrected = df_merged[~df_merged['order_id'].isin(outliers)]

monthly = corrected.groupby('month')['order_value'].sum()
peak = monthly.idxmax()

plt.figure(figsize=(8, 5))
plt.plot(monthly.index.astype(str), monthly.values, marker='o')

plt.xlabel('Month')
plt.ylabel('Revenue')
plt.title(f'Monthly Revenue Trend — Peak: {peak}')
plt.xticks(rotation=45)
plt.tight_layout()

path2 = 'visualizations/monthly_revenue_trend.png'
plt.savefig(path2)
plt.show()

display(Image(filename=path2))

print("Both PNGs saved in the visualizations/ folder.")

